CREATE DATABASE IF NOT EXISTS AltaConstrucoes;
USE AltaConstrucoes;

CREATE TABLE IF NOT EXISTS Emails (
    id INT AUTO_INCREMENT PRIMARY KEY,
    subject VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);